apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-microservice
  template:
    metadata:
      labels:
        app: weather-microservice
    spec:
      containers:
      - name: weather-microservice
        image: apurvvaish/weather-forecast:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENWEATHERMAP_API_KEY
          valueFrom:
            secretKeyRef:
              name: openweathermap-secret
              key: api_key
        - name: OPENWEATHERMAP_API_URL
          valueFrom:
            configMapKeyRef:
              name: openweathermap-config
              key: api_url
        - name: OPENWEATHERMAP_API_WEATHER_URL
          valueFrom:
            configMapKeyRef:
              name: openweathermap-config
              key: weatherUrl
      tolerations:
      - key: "weather-app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule" 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master  
                operator: DoesNotExist 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - weather-microservice
            topologyKey: "kubernetes.io/hostname"
