# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: weather-microservice
spec:
  selector:
    app: weather-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort